language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t everware-base-image .
  - docker run -d --name everware-image everware-base-image

script:
  - docker ps | grep -q everware-image
